### ISSUE TITLE
Clickable links in announcement

### ISSUE THREAD

**Issue by EsdrasXavier** [llkirkwood9/ServerAnnounce#1]
Can you please add the feature of an clickable link in the announcement made by the plugin? I think that would be pretty cool!!

**Comment by llkirkwood9** [comment]
Hello!
     Thanks for taking an interest in the plugin and reaching out to me!
I'm pretty sure this feature is already in there. Here is a link to a
video:
https://drive.google.com/file/d/1MZANtsjNhHMjHO_FJzu8C4f9qn8mk8Gd/view?usp=sharing
of me demonstrating it using the /SAbroadcast command but the same will
work for regular broadcasts. If that is not what you meant then please let
me know and i'll look into adding some more features!

Thanks,
Logan Kirkwood
llkirkwood9@gmail.com

**Comment by EsdrasXavier** [comment]
Thank you. Sorry if this was in the documentation, I ended up not seeing it.
